local u = require("patchy.utils")

vim.keymap.set("n", "<leader>pp", vim.cmd.Ex, { silent = true })
vim.keymap.set("n", "<leader>px", vim.cmd.Sex, { silent = true })
vim.keymap.set("n", "<leader>pv", vim.cmd.Vex, { silent = true })
u.set_n("<C-u>", "<C-u>zz")
u.set_n("<C-d>", "<C-d>zz")
u.set_n("G", "Gzz")
u.set_n("<leader>y", '"+y')
u.set_v("<leader>y", '"+y')
u.set_v("K", ":m '<-2<CR>gv=gv")
u.set_v("J", ":m '>+1<CR>gv=gv")
