(local lsp (require :lspconfig))
(local on-attach (require :patchy/lsp/on_attach))

(lsp.lua_ls.setup { :on_attach on-attach })
(lsp.fennel_ls.setup { :on_attach on-attach })
(lsp.rust_analyzer.setup { :on_attach on-attach })
(lsp.taplo.setup { :on_attach on-attach })
(lsp.nil_ls.setup { :on_attach on-attach })
(lsp.gleam.setup { :on_attach on-attach })
(lsp.clangd.setup { :on_attach on-attach })
(lsp.html.setup { :on_attach on-attach })
(lsp.tsserver.setup { :on_attach on-attach })
