(require :patchy/system/autopairs)
(require :patchy/system/leap)
(require :patchy/system/comment)
(require :patchy/system/fugitive)
(require :patchy/system/surround)
(require :patchy/system/treesitter)
(require :patchy/system/markdown_preview)
